// constants
var AMOUNT_OF_WORDS = 113;
var MIN_AMOUNT_OF_INDIVIDUALS = 1000;
var MIN_DIFFERENT_TYPE_OF_INDIVIDUALS = 10;
var AMOUNT_OF_BITS = 16;
var MAX_VALUE_BITS = 65535;
var MUTATION_PROBABILITY= 7;
var WEIGTH_PERCENTAGE = 45;
var DISTANCE_PERCENTAGE= 55;
var FITNESS_PERCENTAGE=50;
var INDIVIDUALS_PER_REPRODUCTION = 30;
var PLANE_SIZE = 200;
var FONT_MAXIMUM = 10;
var FONT_MINIMUM = 5;
var PLANE_HEIGHT = 50;
var MAX_INDIVIDUALS = 2000;
var BITS_ATTRIBUTES = 8;
var NUMBER_BITS_ATTRIBUTES = 255; 

