// constants
var AMOUNT_OF_WORDS = 150;
var MIN_AMOUNT_OF_INDIVIDUALS = 1000;
var MIN_DIFFERENT_TYPE_OF_INDIVIDUALS = 10;
var AMOUNT_OF_BITS = 16;
var MUTATION_PROBABILITY= 10;
var WEIGTH_PERCENTAGE = 40;
var DISTANCE_PERCENTAGE= 60;
var FITNESS_PERCENTAGE=50;
var INDIVIDUALS_PER_REPRODUCTION = 10;

